### ISSUE TITLE
Allow selection of additional fiat currencies when generating receive QR code

### ISSUE THREAD

**Issue by Max1us** [vergecurrency/vIOS#95]
**Describe the solution you'd like**
When generating a receive QR code, you can only switch between your default fiat currency and XVG. Perhaps there could be a shortlist of additional 'favourite' currencies the function could cycle through.
e.g. XVG > USD > GBP > BTC > XVG...

**Comment by SwenVanZanten** [comment]
The QR code just contains the amount of XVG you want it doesn't create the code with the selected currency.

The link which eventually generates the QR doesn't have such a possibility in it either, and I don't really think it's wise to do so.

But do you think one would ever use something like that?
Like give me 1 usd instead of 0.8 eur 🤔 
It would make things complex.

**Comment by Max1us** [comment]
eBay / Paypal - I end up using it all the time. When I buy something that's listed in another currency, I turn off Paypal's crappy conversion rate from my currency, and have them bill my credit card in USD directly.

So if I was selling something, to make it easier to understand, I could say "pay me 20USD" (for example) and generate a qr code for that. Or if someone was paying me back for something, you don't have to manually convert to xvg, or risk missing a zero :).

**Comment by SwenVanZanten** [comment]
For now this is to complicated.
Better use a third party tool for this.
